version: "3.9"

services:
  app:
    container_name: airminder-ml
    image: airminder
    ports:
      - "9090:9090"
    volumes:
      - airminder-vol:/app
    restart: on-failure
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0']
    #           capabilities: [ gpu ]
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=br0

    #   - traefik.http.routers.infusionDrop.rule=Host(`infusion-drop.ai.newfemme.co`)
    #   - traefik.http.routers.infusionDrop.entrypoints=http
    #   - traefik.http.services.infusionDrop.loadbalancer.server.port=80

# networks:
#   br0:
#     external: true
volumes:
  airminder-vol:
    name: airminder-vol
