version: '3.9'

services:
  app:
    container_name: airminder-ml
    image: ml/airminder:1.0.0
    ports:
      - "9090:9090"
    volumes:
      - webapp-infusion-drop-vol:/app
    restart: on-failure

volumes:
  webapp-infusion-drop-vol:
    name: webapp-infusion-drop-vol
