name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t ghcr.io/${{ github.repository_owner }}/airminder:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository_owner }}/airminder:${{ github.sha }}

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USER: root
        PASS: ${{ secrets.DIGITALOCEAN_ROOT_PASSWORD }}
      run: |
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
          docker pull ghcr.io/${{ github.repository_owner }}/airminder:${{ github.sha }}
          docker stop airminder || true
          docker rm airminder || true
          docker run -d --name airminder -p 9090:9090 ghcr.io/${{ github.repository_owner }}/airminder:${{ github.sha }}
